### ISSUE TITLE
Where can I save, for example, queries?

### ISSUE THREAD

**Issue by kmpm** [marcelo-ochoa/pgadmin4-docker-extension#10]
Where can I save, for example, queries?
All folders seems write protected.

**Comment by marcelo-ochoa** [comment]
If you want to store temporary files /tmp directory is a good location, for example an export that then you download to a local folder of your machine.
If you want to store dump or queries which persists across multiple Docker Desktop restart there is a persistent volume for /var/lib/pgadmin so a good location for your queries could be  /var/lib/pgadmin/storage:
![image](https://user-images.githubusercontent.com/16995718/232030709-97a3e53b-d39b-47d8-a8ca-889b677b86f5.png)
Note that above directory also persist across PGAdmin4 Docker Extensions updates., yesterday I released version 7.0.0 and is really fast.
Marcelo.

**Comment by kmpm** [comment]
Thanks, that will work.
