### ISSUE TITLE
Connect to Postgres running on localhost

### ISSUE THREAD

**Issue by sbulman** [marcelo-ochoa/pgadmin4-docker-extension#12]
Is it possible to connect to Postgres running on localhost? In actual fact, I am running Postgres in Kubernetes Docker Desktop and have port forwarding so if there is a better way to connect within the Docker network that would also be fine.

Thanks,
Si

**Comment by marcelo-ochoa** [comment]
.

**Comment by sbulman** [comment]
Thanks
