### ISSUE TITLE
Permission denied when saving query file

### ISSUE THREAD

**Issue by csulit** [marcelo-ochoa/pgadmin4-docker-extension#14]
![image](https://github.com/marcelo-ochoa/pgadmin4-docker-extension/assets/31933946/8ad47798-14aa-47a3-8e6d-c8ba8425cab4)

**Comment by Evynglais** [comment]
Fixed in PR, but temp workaround is to use /var/lib/pgadmin.

**Comment by marcelo-ochoa** [comment]
See PR example for using a sub-dir on persistent volume.
