### ISSUE TITLE
How to visit pgAdmin4 docker extension server  in external browser？

### ISSUE THREAD

**Issue by yuxiao97** [marcelo-ochoa/pgadmin4-docker-extension#2]
Installed the plugin in docker，it‘s option in docker dashboard only, How to visit pgAdmin4 docker extension server  in external browser？
tks!

**Comment by marcelo-ochoa** [comment]
Sure you can using: http://localhost:9080/browser/
Here is how it look like:
![image](https://user-images.githubusercontent.com/16995718/185176747-91ce74d8-1dca-47ba-a157-5c7256b5a983.png)
Hope this help, Marcelo.
