### ISSUE TITLE
Cannot save files

### ISSUE THREAD

**Issue by don-ny** [marcelo-ochoa/pgadmin4-docker-extension#20]
Hello :-)

It seems impossible to save any files via the "save file" dialog.
Is this by design or am I just missing something?

**Steps to reproduce:**
1) establish connection to any server, open a database and open the query tool
2) write some text
3) klick on the **save** icon
![Screenshot 2024-01-05 223632](https://github.com/marcelo-ochoa/pgadmin4-docker-extension/assets/71487824/3c89c029-3fc3-478f-ba41-d4d6e30d7b9d)

4) give a file name and klick **save**
![Screenshot 2024-01-05 223714](https://github.com/marcelo-ochoa/pgadmin4-docker-extension/assets/71487824/af1b8054-c518-4150-9c9d-4e3ad757a34e)

5) message window shows a **permission denied** error
![Screenshot 2024-01-05 223725](https://github.com/marcelo-ochoa/pgadmin4-docker-extension/assets/71487824/2a19de79-3a42-45f5-bd12-139aa5df5563)

I also noticed that there is no home folder for pgadmin
![Screenshot 2024-01-05 223744](https://github.com/marcelo-ochoa/pgadmin4-docker-extension/assets/71487824/f8481fe7-54c7-4ad4-95b7-2291901399dc)

**My configuration:**
- latest Docker on Windows 11

Your support is greatly appreciated

**Comment by marcelo-ochoa** [comment]
Please see issue https://github.com/marcelo-ochoa/pgadmin4-docker-extension/issues/10
Best regards, Marcelo.

**Comment by don-ny** [comment]
Hey Marcelo,
thanks for the quick reply.

I checked #10 out and I get it - there is a way to store files permanently, thank you for the hint.

**From perspective of Linux Filesystem Hierarchy Standard:**
Is /var/lib really the "right" directory for storing personal/user specific files?
[see Purpose of /var/lib in official linux spec](https://refspecs.linuxfoundation.org/FHS_3.0/fhs-3.0.html#varlibVariableStateInformation)
It just seems to me that using /home/pgadmin/ is much more suitable and I suppose the makers of pgadmin intended the function to be used in exactly that way, hence the error messages.

**From perspective of a basic user:**
As a basic user, one wants to use software like the developer intended.
If one receives such error messages, one just assumes that there is something wrong with the program.
While I appreciate the workaround, a basic user doesn't really care about it and is likely to just stop using it if he can't use the software as intended. 

Just wanted to leave some food for thought - maybe you can bring yourself to incorporate a fix in a future version.
All the best,
Paul
