### ISSUE TITLE
Dark Mode Icon Can Not Be Seen

### ISSUE THREAD

**Issue by wilecoyte78** [marcelo-ochoa/pgadmin4-docker-extension#23]
When in dark mode I cannot see the icon in Docker Desktop:

![image](https://github.com/marcelo-ochoa/pgadmin4-docker-extension/assets/1266992/03507f74-8a73-4687-8303-28d4851e3942)

**Comment by marcelo-ochoa** [comment]
I see that, but unfortunately PG Admin project do not provide a black/white png image for using according to light/dark mode settings.
If you have one I can test it.
Best regards, Marcelo.

**Comment by wilecoyte78** [comment]
![Screenshot 2024-05-31 163534](https://github.com/marcelo-ochoa/pgadmin4-docker-extension/assets/1266992/3e2ca4ad-ed79-45bd-a2ca-75e9cf4a3c36)

![pgadmin](https://github.com/marcelo-ochoa/pgadmin4-docker-extension/assets/1266992/22a82dec-982e-48b2-8674-7626fa5141bd)

**Comment by marcelo-ochoa** [comment]
fixed in commit https://github.com/marcelo-ochoa/pgadmin4-docker-extension/commit/b77e26f3385f418232c8e6b8970c7c7e9773286d please update to latest version 8.8.0 using Docker Desktop Extension update
