### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by boradesanket13** [marcelo-ochoa/pgadmin4-docker-extension#4]
CONTRIBUTING.md is a must read file for a new contributor in any repository before starting to work.

- Add general good practices while starting to work with this specific project.
- Add standard Github workflow commands in the CONTRIBUTING.md (opening issues, get assigned, fork, create clone, add, commit, creating PRs).
- It will provide new potential project contributors with a short guide to how they can help with your project.

**Comment by Sanket1308** [comment]
Kindly assign me this issue under hacktoberfest. I would like to work on it.🚀

**Comment by marcelo-ochoa** [comment]
Added.
