### ISSUE TITLE
PGAdmin4 failed to start on Windows

### ISSUE THREAD

**Issue by ivan-curkovic** [marcelo-ochoa/pgadmin4-docker-extension#6]
Hi, 
I cannot start the extension on my machine:
- Windows 11
- Docker Desktop 4.15.0
- PGAdmin4-docker-extension 6.17.0

Note: it works on mac

### When opening the extension, I receive this message:
> PGAdmin4 failed to start, please close the extension and reopen/reinstall to try again.
![image](https://user-images.githubusercontent.com/114476778/209982847-485fc2c8-1e34-4cd5-be0d-3e247beed26b.png)

### Debugging:
I have opened debugger using `docker extension dev debug mochoa/pgadmin4-docker-extension`. This is the error:

 - **cmd**: "docker exec mochoa_pgadmin4-docker-extension-desktop-extension-pgadmin-1 python3 -c \"import sqlite3;c=sqlite3.connect('/var/lib/pgadmin/pgadmin4.db');u=c.cursor();u.execute('insert or replace into user_preferences (pid,uid,value) values ((SELECT id from preferences where name=?),1,?)',('theme','dark'));c.commit();u.close();c.close()\" || true"
 - _**stderr**: "Traceback (most recent call last):\n File \"<string>\", line 1, in <module>\nsqlite3.IntegrityError: NOT NULL constraint failed: user_preferences.pid\n'true' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n"_

**Comment by marcelo-ochoa** [comment]
Hi @ivan-curkovic 
   Try checking if PGAdmin container is running properly with:

```bash
$ docker exec -ti mochoa_pgadmin4-docker-extension-desktop-extension-pgadmin-1 pwd
/pgadmin4
```

Next try connecting using an external browser using http://localhost:9080/
Once you connect for the first time the sqllite user preference is defined and the extension should work.
6.17 release have a fix at the end of the exec command with _**|| true**_ as fallback action if sqllite fail, but seem that on Windows doesn't work. 
Marcelo.

PD: I just released 6.18 version. I tested it on Windows and open the URL with any browser solve the initial setup problem of the sqllite database.

**Comment by marcelo-ochoa** [comment]
Fixed on [commit](https://github.com/marcelo-ochoa/pgadmin4-docker-extension/commit/3afadd23ddf9f9fffccae386efec45b1131b8099), by default first run will start on light mode, to proper align with Docker Desktop UI mode just close and open again.
Marcelo.

**Comment by ivan-curkovic** [comment]
hi @marcelo-ochoa, it works now. Thank you for the fast response and happy new year :)
