### ISSUE TITLE
Error updating installation

### ISSUE THREAD

**Issue by hlaebe** [marcelo-ochoa/pgadmin4-docker-extension#7]
Hi,
 I'm runnig the extension in Docker Desktop on Windows 10 Pro 22H2..

 Actually I can start the extension, running  v4 6.19. Docker desktop is showing an update, but when I try to update via CLI ,it fails

executing 'docker --context desktop-linux compose -p mochoa_pgadmin4-docker-extension-desktop-extension down --remove-orphans' : exit status 1:
unable to resolve docker endpoint: unexpected end of JSON input

The same when I try to uninstall, though it is calling the same command.

Any ideas how to force removal/update ?

Thx,
 Holger

**Comment by hlaebe** [comment]
Hi Marcelo,

> Update the extension using Docker Desktop GUI doesn't work?
No, that's why I tried via CLI. It shows the same message like CLI.

~~~
 docker extension rm mochoa/pgadmin4-docker-extension:6.19.0
Removing extension mochoa/pgadmin4-docker-extension:6.19.0...
Removing extension containers...
removing extension containers: executing 'docker --context desktop-linux compose -p mochoa_pgadmin4-docker-extension-desktop-extension down --remove-orphans --volumes' : exit status 1:
unable to resolve docker endpoint: unexpected end of JSON input
~~~

I was able to remove compose project,  quite surprising there wre two of them (??).  I've deleted both of them successfully.
But it is still shown in the list of extensions and remove via GUI/CLI leads still to the same error message (see above).

Restarting docker service or windows machine didn't  help.

Any clues ?

**Comment by hlaebe** [comment]
I did some more attempts and found that it is not related to this extension but to docker desktop itself. I couldn't remove any installed extension, so I'll factory reset the installation od docker desktop and restart with a clean system.

Thanks for you help.

**Comment by javaharut** [comment]
After update on MACOS I receive this error and this is second time already. To fix it I need to uninstall and then reinstall again.

`PGAdmin4 failed to start, please close the extension and reopen/reinstall to try again.`

**Comment by marcelo-ochoa** [comment]
@javaharut some times, I don´t know why :( Docker Desktop switch names of the services, I mean instead of:
```bash
$ docker ps
CONTAINER ID   IMAGE                                          COMMAND                  CREATED       STATUS          PORTS                                              NAMES
d15be6e46778   dpage/pgadmin4:6.20                            "/entrypoint.sh"         4 days ago    Up 49 seconds   80/tcp, 443/tcp, 0.0.0.0:9080->9080/tcp            mochoa_pgadmin4-docker-extension-desktop-extension-service
9fe5d92a8992   mochoa/pgadmin4-docker-extension:6.20.0        "/bin/sh -c '/servic…"   4 days ago    Up 48 seconds                                                      mochoa_pgadmin4-docker-extension-desktop-extension-pgadmin4-docker-extension-1
```
  it switch the services and _mochoa/pgadmin4-docker-extension:6.20.0_ runs as _mochoa_pgadmin4-docker-extension-desktop-extension-service_ and _dpage/pgadmin4:6.20_ runs as _mochoa_pgadmin4-docker-extension-desktop-extension-pgadmin4-docker-extension-1_ which obviously doesn't work.
  But I can't reproduce this error repeatedly to report as an issue to the DD extension team.
  Marcelo.

**Comment by marcelo-ochoa** [comment]
Latest release 7.0.0 fix this issue in all cases.
