### ISSUE TITLE
SSH Tunneling issue

### ISSUE THREAD

**Issue by DanielNoveo** [marcelo-ochoa/pgadmin4-docker-extension#8]
Hi, i am trying to add external server with SSH and for an unknown reason it tries to connect to localhost (but tunnel host is an external IP).
Probably, this issue happens because the host in connection tab is not an IP.

<img width="696" alt="img" src="https://user-images.githubusercontent.com/84327038/224029451-ac1fe069-5e88-4da9-b76d-2d7aee143335.png">

Servers without SSH are connected properly

**Comment by marcelo-ochoa** [comment]
I tested this configuration:
![image](https://user-images.githubusercontent.com/16995718/234286902-5a85a1fb-acf8-4ee9-8077-9c1d32c3c021.png)
![image](https://user-images.githubusercontent.com/16995718/234286013-16f7d9f3-e45d-4894-8ea8-23224f4c01ec.png)
it works using password, I don't tested it using identity file.
At server side I see the ssh daemon running:
```
root     11373  1587  0 10:10 ?        00:00:00 sshd: administrador [priv]
adminis+ 11451 11373  0 10:10 ?        00:00:00 sshd: administrador
```
and a forward connection to PostgreSQL (pid 11451):
```
tcp        0      0 127.0.0.1:14024         127.0.0.1:10432         TIME_WAIT   -                   
tcp        0      0 10.1.1.243:34206        10.1.1.239:10432        ESTABLISHED 11451/sshd: adminis 
```
Note that first screenshot defines a target DB at 10.1.1.239:10432, and second screenshot a tunnel ssh server running at 10.1.1.243 port ssh 22.
Marcelo.
