### ISSUE TITLE
Backup/Restore to/from local host system

### ISSUE THREAD

**Issue by 54mu3l** [marcelo-ochoa/pgadmin4-docker-extension#9]
Hi!

Is there any way to backup to my local host system?

I'm running Docker Desktop on MacOS with pgAdmin4-Docker-Extension installed and I need to backup my database to my Mac but I can't find any way to mount to my host system. Is this even possible? If so, how?

<img width="946" alt="Screenshot" src="https://user-images.githubusercontent.com/17022670/231747012-752c066d-247c-4bf8-a044-5c52df103f99.png">

This also applies to the other way around. I quiet often get databases from our customers and I need to restore them into my development environment. But I couldn't find a way to access a backup file from my host computer.

Thank you for your answer.

**Comment by marcelo-ochoa** [comment]
You have quich access to containers files using Docker Desktop Container pane, here an example, first backup one schema using PGAdmin:
![image](https://user-images.githubusercontent.com/16995718/231846321-ffe7fc6b-ad5c-4e86-b421-112a67c5ad2b.png)
once backup is fnished, locate using file explorer, note I am using as destination /tmp/cta.tar, find using Container pane a container **_named pgadmin4_embedded_dd_vm_**:
![image](https://user-images.githubusercontent.com/16995718/231846898-757c2068-0992-45d8-91fc-97b567c7f93e.png)
click on it and use Files tabs to locate /tmp/ directory, finaly use Save:
![image](https://user-images.githubusercontent.com/16995718/231847212-90b4a88a-f416-415c-bca6-4df4551b5209.png)
and choose your local destination.
Import operation is similar but first uploading the file from local folder to DD.
Hope this help, Marcelo.
PD: If pgadmin4_embedded_dd_vm is not shown on Containers pane enable Settings->Extensions->Show Docker Extensions system containers

**Comment by 54mu3l** [comment]
Perfect, this works!
